### ISSUE TITLE
Support php 8.0

### ISSUE THREAD

**Issue by prhost** [foodkit/lalamove-php-api#14]
Hello,

Could you also make it available for the php 8.0 version? I'm running on 8.0 and it works perfectly, but I always need to use the `--ignore-platform-reqs` flag so it doesn't validate the php version. But now laravel 9 supports sympony ^6.0 and Symfony updated to version 6.1 only to php 8.1, breaking my application when updating.

**Comment by coreymcmahon** [comment]
Hi @prhost,

Thanks for your request.

I tried relaxing the PHP version number [here](https://github.com/foodkit/lalamove-php-api/commit/6930235fd6eb941febc394215f508a744cb23823) but it seems there's a dependency conflict somewhere further up the tree (I guess with `"guzzlehttp/guzzle": "^7.4.2"`).

I don't have time to investigate at the moment but if you submit a PR (with passing tests in Circle CI) I'll happily merge and tag for you 🙂

**Comment by coreymcmahon** [comment]
Fixed https://github.com/foodkit/lalamove-php-api/commit/5ca1b92b44a0db6278ff93c05b961cf8abbeccca
