### ISSUE TITLE
Not able to cancel the order 

### ISSUE THREAD

**Issue by thehiddennepali** [foodkit/lalamove-php-api#2]
<pre>Exception &#039;Lalamove\Exceptions\NotFoundException&#039; with message &#039;Client error: `PUT https://sandbox-rest.lalamove.com/v2/orders/132736/cancel` resulted in a `404 Not Found` response&#039; 

there is any thing wrong let me know with cancel endpoint

**Comment by coreymcmahon** [comment]
@thehiddennepali does the order exist?

According to the Lalamove API v2 docs this is the correct endpoint (and HTTP method)
